import { useEffect,useState } from 'react';
import type {ContractKind,ProfileType,CheckResult} from '@ai-runtime/contracts';
type Example={id:string;title:string;kind:ContractKind;payload:unknown};
type Saved={id:string;application_id:string;kind:ContractKind;valid:boolean;report:CheckResult;created_at:string;request_summary:unknown;request_digest:string;replayed?:boolean};
type Health={backend:string;database:string;application_id:string;saved_checks:number;contract_version:string};
async function api<T>(path:string,options:RequestInit={}):Promise<T>{
 const response=await fetch('/api/m0/'+path,{...options,headers:{'Content-Type':'application/json',...options.headers}});
 let data:any;try{data=await response.json();}catch{throw new Error('Backend tidak merespons JSON. Pastikan npm run dev berjalan.');}
 if(!response.ok)throw new Error(`${data.error?.code??response.status}: ${data.error?.message??'Request gagal.'}`);return data as T;
}
const pretty=(x:unknown)=>JSON.stringify(x,null,2);
const newKey=()=>`lab-${crypto.randomUUID()}`;
const phaseNames=[['M0','Kontrak yang bisa dicoba','Schema + FE + BE + PostgreSQL lokal. Tidak ada panggilan provider.'],['M1','Fondasi durable','Execution, admission, budget reservation, dan ledger nyata.'],['M2','Model Gateway','OpenRouter dan pembuktian satu direct adapter.'],['M3','Agent Runtime','Claude, sandbox, tools, lease, dan cancellation.'],['M3.5','Reliability gate','Bukti keamanan, recovery, accounting, dan rollback.'],['M4+','Adopsi & perluasan','Migrasi app, Codex, Gemini, dan capability baru.']];
export function App(){
 const [tab,setTab]=useState('playground');const [health,setHealth]=useState<Health|null>(null);
 const [profiles,setProfiles]=useState<ProfileType[]>([]);const [examples,setExamples]=useState<Example[]>([]);
 const [selected,setSelected]=useState('chat');const [kind,setKind]=useState<ContractKind>('chat');
 const [payload,setPayload]=useState('');const [key,setKey]=useState(newKey);const [saved,setSaved]=useState<Saved|null>(null);
 const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [history,setHistory]=useState<Saved[]>([]);
 const [cursor,setCursor]=useState<string|null>(null);const [schemas,setSchemas]=useState<Record<string,unknown>>({});const [schemaName,setSchemaName]=useState('ChatRequest');const [copied,setCopied]=useState(false);
 useEffect(()=>{let active=true;Promise.all([api<Health>('health'),api<{items:ProfileType[]}>('profiles'),api<{items:Example[]}>('examples'),api<{schemas:Record<string,unknown>}>('contracts')]).then(([h,p,e,c])=>{if(!active)return;setHealth(h);setProfiles(p.items);setExamples(e.items);setSchemas(c.schemas);if(e.items[0])setPayload(pretty(e.items[0].payload));}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[]);
 async function reloadHistory(more=false){try{setBusy(true);const r=await api<{items:Saved[];next_cursor:string|null}>('history'+(more&&cursor?'?cursor='+encodeURIComponent(cursor):''));setHistory(old=>more?[...old,...r.items]:r.items);setCursor(r.next_cursor);setHealth(await api<Health>('health'));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function choose(example:Example){setSelected(example.id);setKind(example.kind);setPayload(pretty(example.payload));setKey(newKey());setSaved(null);setError('');}
 async function validate(){
  setError('');setBusy(true);try{const input=JSON.parse(payload);const r=await api<Saved>('validations',{method:'POST',headers:{'Idempotency-Key':key},body:JSON.stringify({kind,payload:input})});setSaved(r);setHealth(await api<Health>('health'));}
  catch(e){setError(e instanceof SyntaxError?'JSON tidak valid. Periksa tanda kutip, koma, dan kurung.':(e as Error).message);}finally{setBusy(false);}
 }
 function navigate(name:string){setTab(name);setError('');if(name==='history')void reloadHistory();}
 const selectedProfile=(()=>{try{return profiles.find(p=>p.profile===JSON.parse(payload).profile);}catch{return undefined;}})();
 return <div className="shell">
  <aside className="sidebar">
   <a className="brand" href="#" onClick={e=>{e.preventDefault();navigate('playground');}}><span className="brand-mark">ar</span><span>AI Runtime<small>PLATFORM WORKSPACE</small></span></a>
   <div className="workspace"><span className="dot"/> Local development <span className="chip">M0</span></div>
   <div className="nav-label">BUILD & UNDERSTAND</div>
   <nav aria-label="Navigasi utama">{[['playground','01','Contract Lab'],['contracts','02','Schema explorer'],['history','03','Riwayat validasi'],['phases','04','Panduan fase']].map(([id,n,label])=><button key={id} className={tab===id?'nav-item active':'nav-item'} onClick={()=>navigate(id!)}><span>{n}</span>{label}</button>)}</nav>
   <div className="sidebar-note"><span className="tiny-label">BOUNDARY UTAMA</span><h3>App owns workflow.<br/>Platform owns execution.</h3><p>Validasi M0 bukan eksekusi AI. Tidak ada job bisnis yang berpindah ke platform.</p></div>
   <div className="sidebar-bottom"><span className="dot"/> Loopback only <small>127.0.0.1</small></div>
  </aside>
  <main>
   <header className="topbar"><span>Workspace <b>/</b> {tab==='playground'?'Contract Lab':tab==='history'?'Riwayat':tab==='contracts'?'Schemas':'Roadmap'}</span><span className="mode">CONTRACT-ONLY <span className="dot"/></span></header>
   <section className="page">
    <div className="page-heading"><div><div className="eyebrow">MILESTONE ZERO</div><h1>{tab==='playground'?'Uji kontrak, pahami alurnya.':tab==='contracts'?'Satu sumber kontrak.':tab==='history'?'Validasi yang tersimpan.':'Bangun per fase, uji per fase.'}</h1><p>{tab==='playground'?'Coba request aplikasi sebelum menghubungkan provider atau menjalankan agent.':tab==='contracts'?'JSON Schema dihasilkan dari definisi TypeScript yang juga dipakai backend.':tab==='history'?'Data dibaca dari PostgreSQL, bukan daftar sementara di browser.':'Setiap milestone memiliki hasil yang bisa dicoba dan batas yang jelas.'}</p></div><div className="release">v{health?.contract_version??'1.0.0-m0'}<small>LOCAL PREVIEW</small></div></div>
    <div className="status-grid"><div className="status-card"><span className="tiny-label">BACKEND</span><strong><i className={health?'status-dot':'status-dot off'}/>{health?'Terhubung':'Belum terhubung'}</strong><small>Fastify · TypeScript</small></div><div className="status-card"><span className="tiny-label">DATABASE</span><strong><i className={health?'status-dot':'status-dot off'}/>{health?.database??'Memeriksa koneksi'}</strong><small>Namespace terpisah: m0</small></div><div className="status-card"><span className="tiny-label">VALIDASI TERSIMPAN</span><strong><span data-testid="saved-count">{health?.saved_checks??'—'}</span> <small className="inline">records</small></strong><small>Scope: m0-playground</small></div><div className="status-card"><span className="tiny-label">PROVIDER CALLS</span><strong>0<small className="inline">calls</small></strong><small>Eksekusi belum diaktifkan</small></div></div>
    {error&&<div className="error-banner" role="alert"><b>Perlu diperiksa</b><span>{error}</span><button onClick={()=>setError('')} aria-label="Tutup error">×</button></div>}
    {tab==='playground'&&<>
     <div className="section-title"><h2>Pilih skenario</h2><span>01 / SUSUN REQUEST</span></div>
     <div className="scenario-grid">{examples.map((e,i)=><button key={e.id} className={'scenario '+(selected===e.id?'selected':'')} onClick={()=>choose(e)}><span className="scenario-number">0{i+1}</span><strong>{e.title}</strong><small>{e.id==='chat'?'Tanpa job & plugin':e.id==='structured'?'Output dengan schema':e.id==='scribe'?'Job tetap di aplikasi':'Contoh yang harus ditolak'}</small></button>)}</div>
     <div className="work-grid"><section className="panel"><div className="panel-head"><h2>Request editor</h2><span className="tag">JSON</span></div><div className="editor-options"><label>Kontrak<select aria-label="Jenis kontrak" value={kind} onChange={e=>{setKind(e.target.value as ContractKind);setSaved(null);}}><option value="chat">POST /v1/chat · planned</option><option value="generate">POST /v1/generate · planned</option><option value="execution">POST /v1/executions · planned</option></select></label><button className="text-button" onClick={()=>{try{setPayload(pretty(JSON.parse(payload)));}catch{setError('JSON belum valid.');}}}>Format JSON</button></div><textarea aria-label="Payload JSON" className="code-editor" spellCheck={false} value={payload} onChange={e=>{setPayload(e.target.value);setSaved(null);}}/>
      <div className="key-row"><label htmlFor="key">Idempotency-Key</label><div><input id="key" value={key} onChange={e=>setKey(e.target.value)} spellCheck={false}/><button className="text-button" onClick={()=>setKey(newKey())}>Key baru</button></div><small>Key yang sama + payload sama mengembalikan record semula.</small></div>
      <div className="panel-footer"><span>Hanya validasi & simpan metadata</span><button className="primary" onClick={()=>void validate()} disabled={busy||!health}>{busy?'Memeriksa…':'Validasi & simpan'} <span>↗</span></button></div>
     </section>
     <section className="panel result-panel"><div className="panel-head"><h2>Hasil pemeriksaan</h2><span className="step-label">02 / EVALUASI</span></div>
      {!saved?<div className="empty-result"><div className="empty-icon">✓</div><h3>Siap menerima request.</h3><p>Klik validasi untuk mengecek schema dan kecocokan profile. Hasil akan disimpan di PostgreSQL.</p><div className="check-list"><span>01 <b>Schema & field</b></span><span>02 <b>Capability & batas profile</b></span><span>03 <b>Persistence & request ID</b></span></div></div>:<div className="result-content" aria-live="polite"><div className={'verdict '+(saved.valid?'valid':'invalid')}><span>{saved.valid?'✓':'!'}</span><div><strong data-testid="verdict">{saved.valid?'Kontrak valid':'Kontrak ditolak'}</strong><small>{saved.replayed?'Replay · tidak membuat record baru':'Record tersimpan di PostgreSQL'}</small></div></div><dl className="result-meta"><div><dt>Application</dt><dd>{saved.application_id}</dd></div><div><dt>Profile</dt><dd>{saved.report.profile?.profile??'Tidak resolved'}</dd></div><div><dt>Capability</dt><dd>{saved.report.capability??'—'}</dd></div><div><dt>Record ID</dt><dd className="mono">{saved.id}</dd></div></dl>{saved.report.issues.map((issue,i)=><div className="issue" key={i}><code>{issue.path||'/'}</code><strong>{issue.code}</strong><p>{issue.message}</p></div>)}{saved.report.warnings.map((w,i)=><p className="notice" key={i}>{w}</p>)}<button className="secondary full" onClick={()=>navigate('history')}>Lihat riwayat di database →</button></div>}
      <div className="profile-note"><span className="tiny-label">PROFILE YANG DIPILIH</span><strong>{selectedProfile?.title??'Belum ditemukan'}</strong><p>{selectedProfile?.description??'Pilih profile yang tersedia pada skenario.'}</p><div><span>{selectedProfile?.execution_path??'—'}</span><span>{selectedProfile?.runtime_adapter??selectedProfile?.provider_adapter??'—'} · planned</span></div></div>
     </section></div>
     <div className="flow-strip"><b>Alur M0</b><span>Frontend</span><i>→</i><span>Backend validator</span><i>→</i><span>PostgreSQL metadata</span><i>→</i><span>Hasil ke frontend</span><small>Tidak menuju provider</small></div>
    </>}
    {tab==='contracts'&&<section className="panel"><div className="panel-head"><h2>Contract registry</h2><a className="text-button" href="/api/m0/openapi.json" target="_blank" rel="noreferrer">Buka M0 OpenAPI ↗</a></div><div className="schema-tools"><label>Schema<select aria-label="Pilih schema" value={schemaName} onChange={e=>setSchemaName(e.target.value)}>{Object.keys(schemas).map(name=><option key={name}>{name}</option>)}</select></label><button className="secondary" onClick={()=>{void navigator.clipboard.writeText(pretty(schemas[schemaName])).then(()=>{setCopied(true);setTimeout(()=>setCopied(false),1500);}).catch(()=>setError('Clipboard tidak tersedia. Salin dari panel schema.'));}}>{copied?'Tersalin':'Salin schema'}</button></div><p className="schema-disclaimer">Schema /v1 adalah draft kontrak. API /v1 belum dijalankan di M0; endpoint aktif hanya /api/m0/*.</p><pre className="schema-code">{pretty(schemas[schemaName])}</pre></section>}
    {tab==='history'&&<section className="panel"><div className="panel-head"><h2>Metadata validasi</h2><button className="secondary" disabled={busy} onClick={()=>void reloadHistory()}>Refresh dari DB</button></div><div className="table-wrap"><table><thead><tr><th>WAKTU</th><th>KONTRAK</th><th>STATUS</th><th>RECORD</th><th/></tr></thead><tbody>{history.map(row=><tr key={row.id}><td>{new Date(row.created_at).toLocaleString('id-ID')}</td><td>{row.kind}</td><td><span className={'pill '+(row.valid?'pass':'fail')}>{row.valid?'VALID':'INVALID'}</span></td><td className="mono">{row.id.slice(0,13)}…</td><td><button className="text-button" onClick={()=>setSaved(row)}>Detail</button></td></tr>)}</tbody></table></div>{!history.length&&<p className="table-empty">Belum ada validasi. Mulai dari Contract Lab.</p>}{cursor&&<button className="secondary load-more" disabled={busy} onClick={()=>void reloadHistory(true)}>Muat berikutnya</button>}{saved&&<details className="saved-detail" open><summary>Record {saved.id}</summary><pre>{pretty(saved)}</pre></details>}<div className="privacy-note">Yang tersimpan: digest, bentuk request, profile, hasil validasi, dan waktu. Prompt mentah, provider key, dan job bisnis tidak disimpan.</div></section>}
    {tab==='phases'&&<div className="phase-list">{phaseNames.map(([id,title,description])=><section className={'panel phase '+(id==='M0'?'current':'')} key={id}><div className="phase-badge">{id}</div><div><h2>{title}</h2><p>{description}</p></div><span className="tag">{id==='M0'?'BISA DICOBA':'PLANNED'}</span></section>)}<div className="notice">M0 teknis dapat dicoba. Penutupan review arsitektur O11 dan persetujuan produksi tetap memerlukan owner; UI ini tidak mengklaim semua gate selesai.</div><section className="panel command-panel"><h2>Perintah lokal</h2><code>npm run setup</code><p>Siapkan database terpisah dan demo profiles.</p><code>npm run dev</code><p>Jalankan frontend dan backend.</p><code>npm run verify</code><p>Periksa types, kontrak, API/DB, build, dan tautan docs.</p><code>npm run db:inspect</code><p>Lihat metadata langsung dari PostgreSQL.</p></section></div>}
    <footer className="page-footer"><span>AI Runtime Platform · M0 Contract Lab</span><span>Data sintetis saja. Belum untuk produksi.</span></footer>
   </section>
  </main>
 </div>;
}
