import test,{before,after} from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {loadConfig} from '../src/config.js';import {createPool,migrate} from '../src/db.js';import {buildServer} from '../src/server.js';import {examples} from '@ai-runtime/contracts';
const config=loadConfig();const pool=createPool(config);const app=buildServer(pool,config);
const auth={authorization:'Bearer '+config.applications[0]!.token,host:'127.0.0.1:4311'};const other={authorization:'Bearer '+config.applications[1]!.token,host:'127.0.0.1:4311'};
const body={kind:'chat',payload:examples.find(e=>e.id==='chat')!.payload};const keys:string[]=[];
function key(){const x='test-'+randomUUID();keys.push(x);return x;}
async function post(k:string,payload:unknown=body){return app.inject({method:'POST',url:'/api/m0/validations',headers:{...auth,'idempotency-key':k},payload:payload as any});}
before(async()=>{await migrate(pool,config);await app.ready();});
after(async()=>{await app.close();await pool.query('DELETE FROM m0.contract_checks WHERE application_id=$1 AND idempotency_key=ANY($2::text[])',[config.applications[0]!.id,keys]);await pool.end();});
test('health depends on real PostgreSQL',async()=>{const r=await app.inject({url:'/api/m0/health',headers:auth});assert.equal(r.statusCode,200);assert.equal(r.json().database,'PostgreSQL');});
test('missing credentials rejected',async()=>{assert.equal((await app.inject({url:'/api/m0/history',headers:{host:'127.0.0.1'}})).statusCode,401);});
test('cross-origin request rejected',async()=>{assert.equal((await app.inject({url:'/api/m0/history',headers:{...auth,origin:'https://evil.invalid'}})).statusCode,403);});
test('DNS rebinding host rejected',async()=>{assert.equal((await app.inject({url:'/api/m0/history',headers:{...auth,host:'attacker.invalid'}})).statusCode,403);});
test('persist, replay, conflict, and app isolation',async()=>{const k=key();const r=await post(k);assert.equal(r.statusCode,201);const row=r.json();assert.equal(row.valid,true);assert.equal(row.execution_created,false);assert.equal((await post(k)).json().id,row.id);const changed=structuredClone(body);(changed.payload as any).stream=false;assert.equal((await post(k,changed)).statusCode,409);assert.equal((await app.inject({url:'/api/m0/history/'+row.id,headers:other})).statusCode,404);const db=await pool.query('SELECT count(*)::int AS n FROM m0.contract_checks WHERE application_id=$1 AND idempotency_key=$2',[config.applications[0]!.id,k]);assert.equal(db.rows[0].n,1);});
test('20 concurrent duplicate validations create one record',async()=>{const k=key();const rows=await Promise.all(Array.from({length:20},()=>post(k)));assert.equal(rows.filter(r=>r.statusCode===201).length,1);assert.equal(new Set(rows.map(r=>r.json().id)).size,1);});
test('invalid authority field yields persisted INVALID report, not an execution',async()=>{const r=await post(key(),{kind:'chat',payload:examples.find(e=>e.id==='invalid')!.payload});assert.equal(r.statusCode,201);assert.equal(r.json().valid,false);assert.equal(r.json().execution_created,false);});
test('raw prompts are not persisted',async()=>{const fixture=structuredClone(body);const secret='SYNTHETIC_DO_NOT_PERSIST_'+randomUUID();(fixture.payload as any).input.messages[0].content[0].text=secret;const r=await post(key(),fixture);const db=await pool.query('SELECT row_to_json(c) AS row FROM m0.contract_checks c WHERE id=$1',[r.json().id]);assert.equal(JSON.stringify(db.rows[0]).includes(secret),false);});
test('malformed JSON is normalized',async()=>{const r=await app.inject({method:'POST',url:'/api/m0/validations',headers:{...auth,'content-type':'application/json','idempotency-key':key()},payload:'{bad'});assert.equal(r.statusCode,400);assert.equal(r.json().error.code,'INVALID_REQUEST');});
test('payload size bounded',async()=>{const r=await post(key(),{kind:'chat',payload:'x'.repeat(70000)});assert.equal(r.statusCode,413);});
test('history query bounds and page cursor',async()=>{assert.equal((await app.inject({url:'/api/m0/history?limit=999',headers:auth})).statusCode,400);assert.equal((await app.inject({url:'/api/m0/history?cursor=bad',headers:auth})).statusCode,400);const first=(await app.inject({url:'/api/m0/history?limit=1',headers:auth})).json();assert.equal(first.items.length,1);assert.ok(first.next_cursor);const second=(await app.inject({url:'/api/m0/history?limit=1&cursor='+encodeURIComponent(first.next_cursor),headers:auth})).json();assert.notEqual(first.items[0].id,second.items[0].id);});
test('migrations and seed are repeatable without losing history',async()=>{const r=await post(key());await migrate(pool,config);assert.equal((await app.inject({url:'/api/m0/history/'+r.json().id,headers:auth})).statusCode,200);});
test('new server instance sees stored record',async()=>{const r=await post(key());const another=buildServer(pool,config);try{assert.equal((await another.inject({url:'/api/m0/history/'+r.json().id,headers:auth})).json().id,r.json().id);}finally{await another.close();}});
test('unimplemented execution route cannot accidentally call a provider',async()=>{const r=await app.inject({method:'POST',url:'/v1/executions',headers:auth,payload:{}});assert.equal(r.statusCode,404);});

test('deep diagnostic payload rejected before hashing',async()=>{let nested:any={};for(let i=0;i<40;i++)nested={x:nested};const r=await post(key(),{kind:'chat',payload:nested});assert.equal(r.statusCode,400);assert.equal(r.json().error.code,'INVALID_REQUEST');});
test('malformed UUID never reaches a PostgreSQL cast error',async()=>{const r=await app.inject({url:'/api/m0/history/'+ '-'.repeat(36),headers:auth});assert.equal(r.statusCode,404);});
